insert into movie_category values(1,'Action');
insert into movie_category values(2,'Adventure');
insert into movie_category values(3,'Thriller');
insert into movie_category values(4,'Drama');
insert into movie_category values(5,'Romantic');

Insert into role values(1,'Actor');
Insert into role values(2,'Producer');
Insert into role values(3,'Director');


Insert into person values(4,'Steven Speilberg');
Insert into person values(5,'Jack snyder');
Insert into person values(6,'Joe Russo');
Insert into person values(7,'Chris Evans');
Insert into person values(8,'Robert Downey jr');
Insert into person values(9,'Scarlet johansson');
Insert into person values(10,'Chris Hemlsworth');
Insert into person values(11,'Tom Hiddleston');
Insert into person values(12,'Benedict Cumberbatch');
Insert into person values(13,'Tom Holland');
Insert into person values(14,'Ben Affleck');
Insert into person values(15,'Mark Ruffalo');
Insert into person values(16,'Henry cavill');
Insert into person values(17,'TomHanks');
Insert into person values(18,'Christian Bale');
Insert into person values(20,'Anne Hathway');
Insert into person values(19,'Christopher Nolan');
Insert into person values(21,'Heath Ledger');
Insert into movie values(1,'Avengers','2012');
Insert into movie values(2,'Batman Begins','2006');
Insert into movie values(3,'Dark Knight','2008');
Insert into movie values(4,'Dark Knight rises','2010');
Insert into movie values(5,'Man of Steel','2013');
Insert into movie values(6,'Ironman3','2013');
Insert into movie values(7,'Iron Man','2008');
Insert into movie values(8,'Iron Man2','2010');
Insert into movie values(9,'Captain America','2010');
Insert into movie values(10,'Captain America2','2013');
Insert into movie values(11,'Captain America3','2016');
Insert into movie values(12,'Batman v Superman','2015');
Insert into movie values(13,'Justice League','2017');
insert into movie_category_mapping values(1,1,1);
insert into movie_category_mapping values(2,1,2);
insert into movie_category_mapping values(3,2,1);
insert into movie_category_mapping values(4,2,2);
insert into movie_category_mapping values(5,3,1);
insert into movie_category_mapping values(6,3,2);
insert into movie_category_mapping values(7,4,1);
insert into movie_category_mapping values(8,4,2);
insert into movie_category_mapping values(9,5,1);
insert into movie_category_mapping values(10,5,2);
insert into movie_category_mapping values(11,6,1);
insert into movie_category_mapping values(12,6,2);
insert into movie_category_mapping values(13,7,1);
insert into movie_category_mapping values(14,7,2);
insert into movie_category_mapping values(15,8,1);
insert into movie_category_mapping values(16,8,2);
insert into movie_category_mapping values(17,9,1);
insert into movie_category_mapping values(18,9,2);
insert into movie_category_mapping values(19,10,1);
insert into movie_category_mapping values(20,10,2);
insert into movie_category_mapping values(21,11,1);
insert into movie_category_mapping values(22,11,2);
insert into movie_category_mapping values(23,12,1);
insert into movie_category_mapping values(24,12,2);
insert into movie_category_mapping values(25,13,1);
insert into movie_category_mapping values(26,13,2);

insert into movie_cast values(1,1,7,1);
insert into movie_cast values(2,1,8,1);
insert into movie_cast values(3,1,9,1);
insert into movie_cast values(4,1,10,1);
insert into movie_cast values(5,1,11,1);
insert into movie_cast values(6,1,6,2);
insert into movie_cast values(7,1,5,3);

insert into movie_cast values(8,2,7,1);
insert into movie_cast values(9,2,8,1);
insert into movie_cast values(10,2,9,1);
insert into movie_cast values(11,2,10,1);
insert into movie_cast values(12,2,11,1);
insert into movie_cast values(13,2,6,2);
insert into movie_cast values(14,2,5,3);


insert into movie_cast values(15,3,7,1);
insert into movie_cast values(16,3,8,1);
insert into movie_cast values(17,3,9,1);
insert into movie_cast values(18,3,10,1);
insert into movie_cast values(19,3,11,1);
insert into movie_cast values(20,3,6,2);
insert into movie_cast values(21,3,5,3);